/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminNavPanel: typeof import('./src/components/Admin/AdminNavPanel.vue')['default']
    AdminRateCard: typeof import('./src/components/Admin/AdminRateCard.vue')['default']
    AppFooter: typeof import('./src/components/App/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/App/AppHeader.vue')['default']
    AppInput: typeof import('./src/components/App/AppInput.vue')['default']
    ApplicationForm: typeof import('./src/components/Application/ApplicationForm.vue')['default']
    ApplicationItem: typeof import('./src/components/Application/ApplicationItem.vue')['default']
    ApplicationModal: typeof import('./src/components/Application/ApplicationModal.vue')['default']
    ApplicationNotice: typeof import('./src/components/Application/ApplicationNotice.vue')['default']
    ApproveModal: typeof import('./src/components/App/ApproveModal.vue')['default']
    RateIncludes: typeof import('./src/components/Rate/RateIncludes.vue')['default']
    RateItem: typeof import('./src/components/Rate/RateItem.vue')['default']
    RateList: typeof import('./src/components/Rate/RateList.vue')['default']
    RateSettingsModal: typeof import('./src/components/Admin/RateSettingsModal.vue')['default']
    RatesSidebar: typeof import('./src/components/Admin/RatesSidebar.vue')['default']
    RateTypeModal: typeof import('./src/components/Admin/RateTypeModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarItem: typeof import('./src/components/Admin/SidebarItem.vue')['default']
    TabButton: typeof import('./src/components/App/TabButton.vue')['default']
    UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputNumber: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    ULinkBase: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    UTable: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTooltip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
